version: 2.1

orbs:
  node: circleci/node@2.0.1

jobs:
  build:
    docker:
      - circleci/node:10.19.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install yarn
          command: 'curl -o- -L https://yarnpkg.com/install.sh | bash'
      - run:
          name: Install dependencies
          command: 'yarn install'
      - run:
          name: Lint
          command: 'yarn lint'
      - run:
          name: Build
          command: 'yarn build'
